{% set name = "luarocks" %}
{% set version = "3.12.1" %}
{% set sha256 = "f56b85a2a7a481f0321845807b79a05237860b04e4a9d186da632770029b3290" %}
{% set build = 0 %}

# prioritize latest variant via build number
{% if variant == 'latest' %}
{% set build = build + 100 %}
{% endif %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: http://luarocks.github.io/luarocks/releases/luarocks-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build }}
  skip: true  # [win or (target_platform == 'linux-ppc64le' and variant == 'luajit')]
  detect_binary_files_with_prefix: true

  # add build string so packages can depend on luajit variants explicitly:
  string: "luajit_h{{ PKG_HASH }}_{{ build }}"  # [variant == 'luajit']

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - make
    - sed
    - gnuconfig  # [unix]
    - lua               # [build_platform != target_platform and variant == 'latest']
    - luajit-openresty  # [build_platform != target_platform and variant == 'luajit']
    - lua 5.1.*         # [build_platform != target_platform and variant == 'lua51']
  host:
    - lua               # [variant == 'latest']
    - luajit-openresty  # [variant == 'luajit']
    - lua 5.1.*         # [variant == 'lua51']
    - unzip
  run:
    - lua               # [variant == 'latest']
    - luajit-openresty  # [variant == 'luajit']
    - lua 5.1.*         # [variant == 'lua51']
    - unzip

test:
  commands:
    - luarocks config

about:
  home: https://luarocks.org/
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: LuaRocks is the package manager for Lua modulesLuaRocks is the package manager for Lua module

  description: |
    LuaRocks is the package manager for Lua modules.
    It allows you to create and install Lua modules as self-contained
    packages called rocks. You can download and install LuaRocks on Unix and
    Windows.
  doc_url: https://github.com/luarocks/luarocks/wiki/Documentation
  dev_url: https://github.com/luarocks/luarocks/

extra:
  recipe-maintainers:
    - jerowe
    - izahn
    - anjos
