{% set name = "luarocks" %}
{% set version = "3.0.2" %}
{% set sha256 = "3836267eff2f85fb552234e966602b1e649c58f81f47c7de3785e071c8127f5a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: http://luarocks.github.io/luarocks/releases/luarocks-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - lua
    - unzip
  run:
    - lua
    - unzip

test:
  commands:
    - luarocks --lr-path

about:
  home: https://luarocks.org/
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: 'LuaRocks is the package manager for Lua modulesLuaRocks is the package manager for Lua module'

  description: |
      LuaRocks is the package manager for Lua modules.
      It allows you to create and install Lua modules as self-contained
      packages called rocks. You can download and install LuaRocks on Unix and
      Windows.
  doc_url: https://github.com/luarocks/luarocks/wiki/Documentation
  dev_url: https://github.com/luarocks/luarocks/

extra:
  recipe-maintainers:
    - jerowe
