{% set name = "luarocks" %}
{% set version = "3.0.4" %}
{% set sha256 = "1236a307ca5c556c4fed9fdbd35a7e0e80ccf063024becc8c3bf212f37ff0edf" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: http://luarocks.github.io/luarocks/releases/luarocks-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2001
  skip: True  # [win]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - lua
    - unzip
  run:
    - lua
    - unzip

test:
  commands:
    - luarocks --lr-path

about:
  home: https://luarocks.org/
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: 'LuaRocks is the package manager for Lua modulesLuaRocks is the package manager for Lua module'

  description: |
      LuaRocks is the package manager for Lua modules.
      It allows you to create and install Lua modules as self-contained
      packages called rocks. You can download and install LuaRocks on Unix and
      Windows.
  doc_url: https://github.com/luarocks/luarocks/wiki/Documentation
  dev_url: https://github.com/luarocks/luarocks/

extra:
  recipe-maintainers:
    - jerowe
